# Generated by Django 3.0.2 on 2020-01-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('soil_temp', models.FloatField()),
                ('soild_ph', models.IntegerField()),
                ('stifler_id', models.TextField(max_length=14)),
                ('taken_date', models.DateTimeField(auto_now_add=True, verbose_name='taken datetime')),
            ],
        ),
    ]
